# This file relates to internal XMOS infrastructure and should be ignored by external users
---
lib_name: lib_spi
project: '{{lib_name}}'
title: '{{lib_name}}: SPI Library'
version: 4.0.0

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  root_doc: doc/rst/lib_spi.rst
  linkcheck_ignore_regex: ['']
  latex_toc_depth: 3
  latex_secnum_depth: 3
  cognidox_part_number: XM-006232-UG
  doxygen_projects:
    lib_spi:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/rst/lib_spi.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{lib_name}}_v{{version}}'
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{lib_name}}_v{{version}}_readme'
      pdf_short: yes
software:
  cognidox_part_number: XM-007474-SM
