#define STACKWORDS_NONE     0
#define STACKWORDS_TEN      10

#define EIGHT_CLOCK_EDGES_DOUBLED   16

#define CLK_START_END_STACK_LOCATION 9

#define PORT_SETUP_DELAYS_OFFSET 0
#define PORT_INPUT_DELAYS_OFFSET 1
